### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by allx1** [Storj/driveshare-gui#183]
Hi,
I am getting bellow mentioned JavaScript error, when trying to run DriveShare. 
The instalation went smoothly without any error. Does anyone now to fix it?

![capture](https://cloud.githubusercontent.com/assets/17143942/12919894/6ba4a9bc-cf46-11e5-9eeb-c2e06ad00283.PNG)

**Comment by littleskunk** [comment]
The reason for the bug should be fixed with driveshare-gui v0.5.1. It will not repair your settings file. Please delete the corrupted settings.json and start with a new one.

**Comment by keeper151515** [comment]
I am still getting that error did a clean install and reinstall still the same error please help

**Comment by littleskunk** [comment]
The bugfix will not repair your settings file. Please delete the corrupted settings.json and start with a new one.

**Comment by keeper151515** [comment]
where do I find the settings.json?

**Comment by littleskunk** [comment]
%appdata%/DriveShare/settings.json
